package com.agileguard.ai.service;

import com.agileguard.ai.model.EpicContextRequest;
import com.agileguard.ai.model.EpicGenerationRequest;
import com.agileguard.ai.model.EpicGenerationResponse;
import com.agileguard.ai.model.GeneratedStory;
import com.agileguard.ai.model.StoryEnhancementRequest;
import com.agileguard.ai.model.StoryEnhancementResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

/**
 * AI service for three enhanced story editor modes:
 *
 *   Mode A — Create Epic:
 *     Takes a plain-English epic description + team config → calls Gemini
 *     with a structured decomposition prompt → returns fully-formed stories
 *     with all AgileGuard-required fields, sized per developer bandwidth.
 *
 *   Mode B — Create Story (with epic context):
 *     When an epic link is provided, fetches epic context and uses Gemini
 *     to suggest Acceptance Criteria that complement existing stories.
 *
 *   Mode C — Update Story:
 *     Sends current story content + epic context + existing gap findings
 *     to Gemini → returns targeted improvement suggestions per field.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EpicStoryGenerationService {

    private final GeminiClientService geminiClient;
    private final ObjectMapper        objectMapper;

    public static final String DISCLAIMER =
        "⚠️ AI Disclaimer: This content was generated by a Large Language Model (Google Gemini). " +
        "LLMs can hallucinate — they may produce plausible-sounding but inaccurate or incomplete content. " +
        "All generated stories, acceptance criteria, and suggestions must be reviewed, validated, " +
        "and approved by your team before use in any sprint or JIRA board.";

    // ── Mode A: Epic → Stories ─────────────────────────────────────────────

    /**
     * Decomposes an epic description into fully-formed JIRA stories.
     * Sizes stories to developer bandwidth and distributes QA work appropriately.
     */
    public EpicGenerationResponse generateStoriesFromEpic(EpicGenerationRequest req) {
        log.info("Generating stories for epic: '{}' | {} devs, {} QAs, {}SP bandwidth",
                req.getEpicTitle(), req.getNumberOfDevelopers(),
                req.getNumberOfQaEngineers(), req.getDeveloperBandwidthSp());

        String prompt = buildEpicDecompositionPrompt(req);
        String raw    = geminiClient.generateContent(prompt);
        return parseEpicResponse(raw, req);
    }

    // ── Mode B: New Story — Epic Context AC ───────────────────────────────

    /**
     * Suggests Acceptance Criteria for a new story based on its parent epic.
     * Avoids duplicating scenarios already covered by existing epic stories.
     */
    public List<String> suggestAcFromEpicContext(EpicContextRequest req) {
        log.info("Suggesting AC from epic context: epic='{}', story='{}'",
                req.getEpicKey(), req.getStoryTitle());

        String prompt = buildEpicContextAcPrompt(req);
        String raw    = geminiClient.generateContent(prompt);
        return parseAcList(raw);
    }

    // ── Mode C: Update Story — Enhancement Suggestions ────────────────────

    /**
     * Analyses an existing story against its epic context and current gap findings,
     * then returns targeted improvement suggestions for every field.
     */
    public StoryEnhancementResponse suggestEnhancements(StoryEnhancementRequest req) {
        log.info("Suggesting enhancements for story: '{}'", req.getIssueKey());

        String prompt = buildEnhancementPrompt(req);
        String raw    = geminiClient.generateContent(prompt);
        return parseEnhancementResponse(raw, req.getIssueKey());
    }

    // ── Prompt builders ────────────────────────────────────────────────────

    private String buildEpicDecompositionPrompt(EpicGenerationRequest req) {
        int totalBandwidth = req.getNumberOfDevelopers() * req.getDeveloperBandwidthSp();
        int qaCount        = req.getNumberOfQaEngineers();

        return """
            You are an expert Agile Product Owner and Solution Architect working within the SAFe framework.
            Analyse the following Epic and decompose it into well-formed JIRA user stories.

            EPIC DETAILS:
            Title: %s
            Description: %s
            Business Line: %s
            Priority: %s
            Sprint: %s
            Components: %s
            Fix Versions: %s
            Team Names: %s

            TEAM CONFIGURATION:
            Developers: %d (bandwidth per sprint: %d SP each = %d SP total)
            QA Engineers: %d
            Epic Key: %s

            YOUR TASK:
            1. Identify ALL functional areas this epic covers
            2. Generate stories so that the total SP fits within team bandwidth (%d SP total dev capacity)
            3. Create QA/test stories for each major feature if QA count > 0
            4. Every story must have ALL required fields:
               - title (user-story format: "As a [role], I want [goal] so that [benefit]")
               - description (detailed, min 30 words)
               - acceptanceCriteria (3-5 Given/When/Then criteria)
               - issueType (Story | Task)
               - priority (%s)
               - businessLine (%s)
               - storyPoints (Fibonacci: 1,2,3,5,8,13 — never > 13 per story)
               - epicLink (%s)
               - suggestedAssigneeRole (Developer | QA)
               - rationale (why this story exists)
               - labels (technical tags)
               - storyIndex (1-based)

            RULES:
            - Split any story > 13SP into smaller stories
            - Each developer story must be independently deliverable
            - QA stories should reference which developer story they test
            - Do NOT generate duplicates or overlapping scope
            - Use business-readable language in titles and AC

            Return ONLY a valid JSON object. No markdown, no code fences:
            {
              "epicAnalysis": "<2-3 sentence scope analysis>",
              "totalEstimatedPoints": <sum of all story points>,
              "estimatedSprints": <ceiling(totalSP / totalBandwidth)>,
              "developerStoryCount": <count>,
              "qaStoryCount": <count>,
              "recommendations": "<team or scope recommendations>",
              "stories": [
                {
                  "storyIndex": 1,
                  "title": "As a ...",
                  "description": "...",
                  "acceptanceCriteria": "Given ...,\\nWhen ...,\\nThen ...\\n\\nGiven ...",
                  "issueType": "Story",
                  "priority": "%s",
                  "businessLine": "%s",
                  "storyPoints": 5,
                  "epicLink": "%s",
                  "suggestedAssigneeRole": "Developer",
                  "rationale": "...",
                  "labels": ["feature", "api"],
                  "components": %s,
                  "fixVersions": %s,
                  "teamNames": %s
                }
              ]
            }
            """.formatted(
                req.getEpicTitle(), req.getEpicDescription(),
                orEmpty(req.getBusinessLine()), orEmpty(req.getPriority()),
                orEmpty(req.getSprintName()),
                listToStr(req.getComponents()), listToStr(req.getFixVersions()),
                listToStr(req.getTeamNames()),
                req.getNumberOfDevelopers(), req.getDeveloperBandwidthSp(), totalBandwidth,
                req.getNumberOfQaEngineers(), orEmpty(req.getEpicKey()),
                totalBandwidth,
                orEmpty(req.getPriority()), orEmpty(req.getBusinessLine()),
                orEmpty(req.getEpicKey()),
                orEmpty(req.getPriority()), orEmpty(req.getBusinessLine()),
                orEmpty(req.getEpicKey()),
                listToJson(req.getComponents()),
                listToJson(req.getFixVersions()),
                listToJson(req.getTeamNames())
        );
    }

    private String buildEpicContextAcPrompt(EpicContextRequest req) {
        String existing = req.getExistingStorySummaries() != null && !req.getExistingStorySummaries().isEmpty()
                ? String.join("\n- ", req.getExistingStorySummaries())
                : "None yet";
        return """
            You are an expert Agile Quality Engineer generating Acceptance Criteria.

            The developer is writing a NEW story that belongs to this Epic:
            Epic Key: %s
            Epic Name: %s
            Epic Description: %s

            NEW STORY BEING WRITTEN:
            Title: %s
            Description: %s
            Business Line: %s
            Issue Type: %s

            EXISTING STORIES IN THIS EPIC (do NOT duplicate their AC):
            - %s

            YOUR TASK:
            Generate 4-6 Acceptance Criteria in Given/When/Then format for the new story.
            - Cover the happy path, error scenarios, boundary conditions, and non-functional concerns
            - Each criterion must be independently testable
            - Consider how this story integrates with the epic's overall goal
            - Avoid scenarios already covered by existing stories in the epic

            Return ONLY a JSON array of strings. No markdown, no extra text:
            ["Given ..., When ..., Then ...", "Given ..., When ..., Then ..."]
            """.formatted(
                orEmpty(req.getEpicKey()), orEmpty(req.getEpicName()),
                orEmpty(req.getEpicDescription()),
                req.getStoryTitle(), orEmpty(req.getStoryDescription()),
                orEmpty(req.getBusinessLine()), orEmpty(req.getIssueType()),
                existing
        );
    }

    private String buildEnhancementPrompt(StoryEnhancementRequest req) {
        String gaps = req.getExistingGapMessages() != null && !req.getExistingGapMessages().isEmpty()
                ? String.join("\n- ", req.getExistingGapMessages())
                : "No gap findings available";
        return """
            You are an expert Agile Quality Coach reviewing and improving an existing JIRA story.

            CURRENT STORY:
            Issue Key: %s
            Title: %s
            Description: %s
            Acceptance Criteria: %s
            Issue Type: %s | Status: %s | Story Points: %s
            Priority: %s | Business Line: %s

            LINKED EPIC CONTEXT:
            Epic Key: %s | Epic Name: %s
            Epic Description: %s

            EXISTING GAP FINDINGS FROM AGILEGUARD:
            - %s

            YOUR TASK:
            1. Assess the current quality (score 0-100)
            2. Identify specific problems and provide actionable fixes
            3. Rewrite the description and AC to meet AgileGuard standards
            4. Estimate the projected score after applying your suggestions
            5. Identify missing acceptance criteria scenarios given the epic context
            6. Check alignment between this story and the epic goal

            Return ONLY a valid JSON object. No markdown, no code fences:
            {
              "qualityScore": <current 0-100>,
              "improvedScore": <projected after suggestions 0-100>,
              "summaryAssessment": "<paragraph overall assessment>",
              "improvedTitle": "<rewritten title in user-story format>",
              "improvedDescription": "<rewritten description, min 30 words>",
              "improvedAcceptanceCriteria": ["Given ..., When ..., Then ...", ...],
              "suggestedStoryPoints": <fibonacci number>,
              "storyPointRationale": "<why this estimate>",
              "epicContextInsight": "<how this story contributes to the epic>",
              "missingScenarios": ["<scenario not currently covered>", ...],
              "issues": [
                {
                  "severity": "<CRITICAL|ERROR|WARNING|SUGGESTION>",
                  "field": "<fieldName>",
                  "problem": "<what is wrong>",
                  "suggestion": "<how to fix it>"
                }
              ]
            }
            """.formatted(
                orEmpty(req.getIssueKey()), orEmpty(req.getTitle()),
                orEmpty(req.getDescription()), orEmpty(req.getAcceptanceCriteria()),
                orEmpty(req.getIssueType()), orEmpty(req.getStatus()),
                req.getStoryPoints() != null ? req.getStoryPoints() : "Not set",
                orEmpty(req.getPriority()), orEmpty(req.getBusinessLine()),
                orEmpty(req.getEpicLink()), orEmpty(req.getEpicName()),
                orEmpty(req.getEpicDescription()),
                gaps
        );
    }

    // ── Response parsers ───────────────────────────────────────────────────

    private EpicGenerationResponse parseEpicResponse(String raw, EpicGenerationRequest req) {
        try {
            String clean = stripFences(raw);
            JsonNode root = objectMapper.readTree(clean);

            List<GeneratedStory> stories = new ArrayList<>();
            JsonNode storiesNode = root.path("stories");
            if (storiesNode.isArray()) {
                for (JsonNode s : storiesNode) {
                    GeneratedStory story = GeneratedStory.builder()
                        .storyIndex(s.path("storyIndex").asInt())
                        .title(s.path("title").asText())
                        .description(s.path("description").asText())
                        .acceptanceCriteria(s.path("acceptanceCriteria").asText())
                        .issueType(s.path("issueType").asText("Story"))
                        .priority(s.path("priority").asText(req.getPriority()))
                        .businessLine(s.path("businessLine").asText(req.getBusinessLine()))
                        .storyPoints(s.path("storyPoints").asInt(3))
                        .epicLink(s.path("epicLink").asText(req.getEpicKey()))
                        .sprintName(req.getSprintName())
                        .sprintId(req.getSprintId())
                        .suggestedAssigneeRole(s.path("suggestedAssigneeRole").asText("Developer"))
                        .rationale(s.path("rationale").asText())
                        .components(parseStringList(s.path("components")))
                        .fixVersions(parseStringList(s.path("fixVersions")))
                        .labels(parseStringList(s.path("labels")))
                        .teamNames(parseStringList(s.path("teamNames")))
                        .build();
                    stories.add(story);
                }
            }

            return EpicGenerationResponse.builder()
                .epicTitle(req.getEpicTitle())
                .epicKey(req.getEpicKey())
                .epicAnalysis(root.path("epicAnalysis").asText())
                .totalEstimatedPoints(root.path("totalEstimatedPoints").asInt())
                .estimatedSprints(root.path("estimatedSprints").asInt(1))
                .developerStoryCount(root.path("developerStoryCount").asInt())
                .qaStoryCount(root.path("qaStoryCount").asInt())
                .recommendations(root.path("recommendations").asText())
                .stories(stories)
                .disclaimer(DISCLAIMER)
                .build();

        } catch (Exception e) {
            log.error("Failed to parse epic generation response: {}", e.getMessage());
            return buildMockEpicResponse(req);
        }
    }

    @SuppressWarnings("unchecked")
    private List<String> parseAcList(String raw) {
        try {
            return objectMapper.readValue(stripFences(raw), List.class);
        } catch (Exception e) {
            log.error("Failed to parse AC list response: {}", e.getMessage());
            return List.of(
                "Given [context from epic], When [specific action], Then [expected outcome]",
                "Given an error condition, When the action fails, Then a meaningful error is shown",
                "Given valid data, When the feature is used, Then it integrates correctly with the epic"
            );
        }
    }

    private StoryEnhancementResponse parseEnhancementResponse(String raw, String issueKey) {
        try {
            String clean = stripFences(raw);
            JsonNode root = objectMapper.readTree(clean);

            List<StoryEnhancementResponse.EnhancementIssue> issues = new ArrayList<>();
            for (JsonNode n : root.path("issues")) {
                issues.add(StoryEnhancementResponse.EnhancementIssue.builder()
                    .severity(n.path("severity").asText())
                    .field(n.path("field").asText())
                    .problem(n.path("problem").asText())
                    .suggestion(n.path("suggestion").asText())
                    .build());
            }

            return StoryEnhancementResponse.builder()
                .issueKey(issueKey)
                .qualityScore(root.path("qualityScore").asInt(50))
                .improvedScore(root.path("improvedScore").asInt(80))
                .summaryAssessment(root.path("summaryAssessment").asText())
                .improvedTitle(root.path("improvedTitle").asText())
                .improvedDescription(root.path("improvedDescription").asText())
                .improvedAcceptanceCriteria(parseStringList(root.path("improvedAcceptanceCriteria")))
                .suggestedStoryPoints(root.path("suggestedStoryPoints").isNull()
                        ? null : root.path("suggestedStoryPoints").asInt())
                .storyPointRationale(root.path("storyPointRationale").asText())
                .epicContextInsight(root.path("epicContextInsight").asText())
                .missingScenarios(parseStringList(root.path("missingScenarios")))
                .issues(issues)
                .disclaimer(DISCLAIMER)
                .build();

        } catch (Exception e) {
            log.error("Failed to parse enhancement response: {}", e.getMessage());
            return StoryEnhancementResponse.builder()
                .issueKey(issueKey).qualityScore(50).improvedScore(75)
                .summaryAssessment("AI analysis encountered a parsing issue. Please review manually.")
                .issues(List.of()).missingScenarios(List.of())
                .improvedAcceptanceCriteria(List.of()).disclaimer(DISCLAIMER).build();
        }
    }

    // ── Mock responses for local dev ───────────────────────────────────────

    private EpicGenerationResponse buildMockEpicResponse(EpicGenerationRequest req) {
        int devBw   = req.getNumberOfDevelopers() * req.getDeveloperBandwidthSp();
        int numStories = Math.max(3, req.getNumberOfDevelopers() * 2);
        List<GeneratedStory> stories = new ArrayList<>();
        for (int i = 1; i <= numStories; i++) {
            boolean isQa = req.getNumberOfQaEngineers() > 0 && i == numStories;
            stories.add(GeneratedStory.builder()
                .storyIndex(i)
                .title("As a user, I want feature " + i + " of " + req.getEpicTitle()
                        + " so that I can achieve the epic goal")
                .description("Implement feature " + i + " as part of the " + req.getEpicTitle()
                        + " epic. This covers the " + (isQa ? "testing" : "development") + " aspect.")
                .acceptanceCriteria("Given the system is running,\nWhen feature " + i
                        + " is used,\nThen the expected outcome occurs.\n\n"
                        + "Given an error condition,\nWhen it occurs,\nThen a clear message is shown.")
                .issueType(isQa ? "Task" : "Story")
                .priority(req.getPriority() != null ? req.getPriority() : "Medium")
                .businessLine(req.getBusinessLine())
                .storyPoints(isQa ? 3 : 5)
                .epicLink(req.getEpicKey())
                .sprintName(req.getSprintName())
                .suggestedAssigneeRole(isQa ? "QA" : "Developer")
                .rationale("Required to deliver " + req.getEpicTitle() + " functionality")
                .components(req.getComponents())
                .fixVersions(req.getFixVersions())
                .teamNames(req.getTeamNames())
                .build());
        }
        return EpicGenerationResponse.builder()
            .epicTitle(req.getEpicTitle()).epicKey(req.getEpicKey())
            .epicAnalysis("The epic covers " + numStories + " distinct functional areas requiring "
                    + req.getNumberOfDevelopers() + " developers and "
                    + req.getNumberOfQaEngineers() + " QA engineers.")
            .totalEstimatedPoints(numStories * 5)
            .estimatedSprints((int) Math.ceil(numStories * 5.0 / devBw))
            .developerStoryCount(numStories - (req.getNumberOfQaEngineers() > 0 ? 1 : 0))
            .qaStoryCount(req.getNumberOfQaEngineers() > 0 ? 1 : 0)
            .recommendations("Consider splitting into two sprints for cleaner delivery boundaries.")
            .stories(stories).disclaimer(DISCLAIMER).build();
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private String stripFences(String raw) {
        if (raw == null) return "{}";
        return raw.replaceAll("```json\\s*", "").replaceAll("```\\s*", "").trim();
    }

    private List<String> parseStringList(JsonNode node) {
        List<String> result = new ArrayList<>();
        if (node != null && node.isArray()) {
            node.forEach(n -> result.add(n.asText()));
        }
        return result;
    }

    private String orEmpty(String v) { return v != null ? v : ""; }

    private String listToStr(List<String> list) {
        return list != null && !list.isEmpty() ? String.join(", ", list) : "None";
    }

    private String listToJson(List<String> list) {
        if (list == null || list.isEmpty()) return "[]";
        try { return objectMapper.writeValueAsString(list); }
        catch (Exception e) { return "[]"; }
    }
}
