package com.agileguard.ai.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * A fully-formed JIRA story generated by the AI from an epic description.
 * Contains all AgileGuard-required fields ready for direct submission to JIRA.
 */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class GeneratedStory {

    private String  title;                // Story summary / title
    private String  description;          // Full user-story format description
    private String  acceptanceCriteria;   // Given/When/Then format AC
    private String  issueType;            // Story | Task
    private String  priority;
    private String  businessLine;
    private Integer storyPoints;          // AI-estimated effort
    private String  epicLink;             // Links back to the parent epic key
    private String  sprintName;
    private Long    sprintId;
    private String  suggestedAssigneeRole;// "Developer" | "QA" — who should own it

    private List<String> components;
    private List<String> fixVersions;
    private List<String> labels;
    private List<String> teamNames;

    /** AI reasoning for why this story exists and its estimated effort. */
    private String rationale;

    /** Story index within the epic (1-based). */
    private int storyIndex;
}
